setwd("~/Coursera/ExploratoryAssignment1")
Table <- read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F, sep=';')
colnames(Table) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
Table$Date<- as.Date(Table$Date, format="%d/%m/%Y" )
dateTime <- strptime( paste(Table$Date,Table$Time), format="%Y-%m-%d %H:%M:%S")
png("Plot4.png")
par(mfrow=c(2,2))
plot(dateTime,Table$Global_active_power, ylab="Global Active Power(kilowatts)", type="l")
plot(dateTime,Table$Voltage, ylab="Voltage",xlab="dateTime", type="l")
plot(dateTime,Table$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering", col="black")
lines(dateTime,Table$Sub_metering_2,type="l",col="red")
points(dateTime,Table$Sub_metering_3,type="l", col="blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
plot(dateTime,Table$Global_reactive_power, xlab="datetime", ylab="Global_reactive_power", type="l")
dev.off()