setwd("~/Coursera/ExploratoryAssignment1")
Table <- read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F, sep=';')
colnames(Table) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
Table$Date<- as.Date(Table$Date, format="%d/%m/%Y" )
dateTime <- strptime( paste(Table$Date,Table$Time), format="%Y-%m-%d %H:%M:%S")
png("Plot3.png")
with(Table, plot(dateTime,Table$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering", col="black"))
with(Table, lines(dateTime,Table$Sub_metering_2,type="l",col="red"))
with(Table, points(dateTime,Table$Sub_metering_3,type="l", col="blue"))
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
dev.off()